SCREEN_SIZE = (800, 600)

BALL_RADIUS = 10

WALL_WIDTH = 10
WALL_HEIGHT = SCREEN_SIZE[1] - 50

BALL_START_POS_X = 20
BALL_START_POS_Y = SCREEN_SIZE[1] / 2
WALL_START_POS_Y = SCREEN_SIZE[1] / 2
WALL_START_POS_X = SCREEN_SIZE[0] - WALL_WIDTH * 2
